version: '3.8'
services:
  productos-service:
    build:
      context: ./productos-service
    container_name: productos-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge